### Create

POST http://localhost:3003/competition/create
Content-Type: application/json

{
    "name": "200m rasos"    
}

### insert result


POST http://localhost:3003/results/insert
Content-Type: application/json

{
    "competicao": "Lançamento de Dardo",
    "atleta": "João de Atlet",
    "value": 78.43,
    "unidade": "m"   
}

###ranking

GET http://localhost:3003/results/ranking
Content-Type: application/json

{
    "competicao": "100m rasos" 
}

###close

PUT http://localhost:3003/competition/close
Content-Type: application/json

{
    "name": "200m rasos" 
}

